### ISSUE TITLE
Initial Android Development

### ISSUE THREAD

**Issue by akbarsigit** [ranggarahman/body-buddy#15]

**Comment by ranggarahman** [comment]
## Basic Login Screen
### 06-03-2023


![Image](https://user-images.githubusercontent.com/79177708/223150437-c79b3f4e-3892-42b0-962d-dd1789c96ee1.jpg)

Still missing functionalities. Need to specify what other sections should be made.

**Comment by ranggarahman** [comment]
#25

**Comment by ranggarahman** [comment]
#26

**Comment by ranggarahman** [comment]
#27
